version: "3"

services:
  mongodb:
    image: mongo
    ports:
      - "27017"
    networks:
      - pixel-network
    volumes:
      - mongodb_data:/data/db

  backendpixelapp:
    build:
      context: ./
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - pixel-network
    environment:
      MONGO_URL: mongodb://mongodb:27017

networks:
  pixel-network:
    driver: bridge

volumes:
  mongodb_data:
